### PR TITLE
server: enable CORS

### LINKED ISSUE #7: server: enable CORS
This is pretty necessary for anyone building a SPA.

### PR DESCRIPTION
**Pull request by matthecarl**
Fixes #7

Is this okay or would you prefer to have the cors middleware module?

### CODE REVIEW

**Comment by dominicbarnes** [comment]
@PerStirpes thank you very much for your contribution!

I'd actually prefer the middleware module if you don't mind. That should also address the lint issues that came up during the Travis test. (you can fix locally with `npm test -- --fix` as well)

**Comment by dominicbarnes** [comment]
Thanks @PerStirpes! I had no idea anyone besides me was using this API, so I'd really love to hear any additional feedback you might have. (it's also my first GraphQL API, so _plenty_ of room to improve)

**Comment by dominicbarnes** [comment]
Released with v0.6.0

**Comment by matthecarl** [comment]
You're welcome @dominicbarnes and thank you for accepting my pr.

I wouldn't be able to provide any specific feedback on your GraphQL implementation, as GraphQL is still very new to me. But, out of curiosity, what tradeoffs did you consider when you decided to use lokijs? 

FWIW, you can simplify your [Array.from](https://github.com/dominicbarnes/pokemongo-api/blob/42f8a318b108321a62504ebe62c2b7eb11645ac6/scripts/mine.js#L63) call by passing your mapFn in as a param. The main difference is that an intermediate array would not be created.

**Comment by dominicbarnes** [comment]
@PerStirpes I started off using just hand-rolling a lot of the metadata structure. For example, starting with arrays and constructing `Map`s to index by specific fields. I decided that I wanted something a bit more structured, offering functionality like a database but keeping it in memory, and also not having to maintain it myself. LokiJS was the first thing I came across and I like it's pretty straightforward API.

As for that `Array.from`, I always forget that it accepts a `mapFn`. I'd gladly accept a PR for that change, but I may also just get to it over the weekend.

**Pull request merged**
